import streamlit as st
import json
import csv
import io
from datetime import datetime, timedelta
from pathlib import Path
import urllib.parse
from collections import Counter

# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="PhillyCulture — Philadelphia Performing Arts",
    page_icon="🎭",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ── Category colors ──────────────────────────────────────────────────────────
CAT_COLORS = {
    "musical": "#ff6b9d",
    "theater": "#ffa44f",
    "dance": "#4fd1c5",
    "ballet": "#f687b3",
    "jazz": "#63b3ed",
    "classical": "#d6a0ff",
    "opera": "#fc8181",
    "concert": "#68d391",
    "performance": "#a0aec0",
}

CAT_ICONS = {
    "musical": "🎵", "theater": "🎭", "dance": "💃", "ballet": "🩰",
    "jazz": "🎷", "classical": "🎻", "opera": "🎤", "concert": "🎶",
    "performance": "🎪",
}

CATEGORIES = ["all", "musical", "theater", "dance", "ballet", "jazz", "classical", "opera", "concert", "performance"]


# ── Load seed events as fallback ─────────────────────────────────────────────
import sys
sys.path.insert(0, str(Path(__file__).parent / "scraper"))
try:
    from seed_events import get_seed_events
    FALLBACK_EVENTS = get_seed_events()
except Exception:
    FALLBACK_EVENTS = []


# ── Event sanitization (last line of defense) ────────────────────────────────
_JUNK_PHRASES = [
    "no upcoming events", "no events", "search form", "no results",
    "sign up for", "subscribe to", "cookie", "privacy policy",
    "page not found", "404", "coming soon", "start date", "e.g.,",
    "placeholder", "select date", "filter by", "sort by",
    "javascript", "enable javascript", "load more", "click here",
]

def _is_valid_event(event):
    """Filter out scraper artifacts and junk entries at display time."""
    if not isinstance(event, dict):
        return False
    title = (event.get("title") or "").strip()
    if not title or len(title) < 3:
        return False
    title_low = title.lower()
    if any(phrase in title_low for phrase in _JUNK_PHRASES):
        return False
    # Must have at least a plausible title (some alpha characters)
    if sum(1 for c in title if c.isalpha()) < 3:
        return False
    return True

def _sanitize_event(event):
    """Clean up event fields: replace None with defaults, strip garbage display text."""
    if not isinstance(event, dict):
        return event
    # Clean garbage date_display
    dd = (event.get("date_display") or "")
    if "start date" in dd.lower() or "e.g." in dd.lower():
        event["date_display"] = ""
    return event


import re as _re

def _normalize_title(title):
    """Normalize a title for fuzzy matching."""
    return _re.sub(r'[^a-z0-9]+', ' ', (title or "").lower()).strip()


def _build_description_lookup():
    """Build a title -> description lookup from seed events."""
    lookup = {}
    for e in FALLBACK_EVENTS:
        desc = e.get("description", "")
        if desc and len(desc) > 30:
            key = _normalize_title(e.get("title", ""))
            if key:
                lookup[key] = desc
    return lookup

_SEED_DESC_LOOKUP = _build_description_lookup()


def _enrich_descriptions(events):
    """Fill in missing descriptions from seed data and venue knowledge.

    This is the last line of defense — runs at display time to ensure
    every event tile has useful content regardless of scraper output.
    """
    for event in events:
        desc = (event.get("description") or "").strip()
        if desc and len(desc) > 40:
            continue  # Already has a real description

        # Strategy 1: Match against seed event descriptions by title
        norm = _normalize_title(event.get("title", ""))
        if norm and norm in _SEED_DESC_LOOKUP:
            event["description"] = _SEED_DESC_LOOKUP[norm]
            continue

        # Strategy 2: Partial match — check if seed title is contained
        for seed_key, seed_desc in _SEED_DESC_LOOKUP.items():
            if len(seed_key) > 8 and (seed_key in norm or norm in seed_key):
                event["description"] = seed_desc
                break
        else:
            # Strategy 3: No seed match — leave description as-is (fallback
            # will be generated by event_description() at render time)
            pass

    return events


# ── Load events ──────────────────────────────────────────────────────────────
@st.cache_data(ttl=300)
def load_events():
    json_path = Path(__file__).parent / "data" / "events.json"
    try:
        with open(json_path) as f:
            data = json.load(f)
        events = data.get("events", [])
        if len(events) == 0:
            raise ValueError("Empty events")
    except Exception:
        data = {
            "last_updated": datetime.utcnow().isoformat() + "Z",
            "sources": sorted({e.get("source", "") for e in FALLBACK_EVENTS if e.get("source")}),
            "events": list(FALLBACK_EVENTS),
            "scrape_report": {"successes": ["Using seed data"], "failures": [], "warnings": []},
        }
    # Sanitize: filter junk, clean fields
    data["events"] = [_sanitize_event(e) for e in data.get("events", []) if _is_valid_event(e)]
    # Enrich: fill missing descriptions from seed data
    data["events"] = _enrich_descriptions(data["events"])
    return data


# ── Helpers ──────────────────────────────────────────────────────────────────
def _s(event, key, default=""):
    """Safely get a string field from an event, never returning None."""
    val = event.get(key)
    return val if val is not None else default


def _cats(event):
    """Safely get categories list from an event, never returning None."""
    val = event.get("categories")
    return val if isinstance(val, list) else []


def _parse_date(date_str):
    """Parse a YYYY-MM-DD string to a date object, or None on failure."""
    if not date_str:
        return None
    try:
        return datetime.strptime(date_str, "%Y-%m-%d").date()
    except (ValueError, TypeError):
        return None


def _event_dates(event):
    """Return (start_date, end_date) as date objects. end defaults to start."""
    start = _parse_date(_s(event, "date_start"))
    end = _parse_date(_s(event, "date_end")) or start
    return start, end


def get_month_key(iso_str):
    if not iso_str:
        return "Unknown"
    try:
        return datetime.strptime(iso_str, "%Y-%m-%d").strftime("%B %Y")
    except Exception:
        return "Unknown"


def today_str():
    return datetime.now().strftime("%Y-%m-%d")


def is_past(event):
    _start, end = _event_dates(event)
    if end is None:
        return False
    return end < datetime.now().date()


def is_current_or_future(event):
    return not is_past(event)


def is_this_week(event):
    start, end = _event_dates(event)
    if start is None:
        return False
    today = datetime.now().date()
    end_of_week = today + timedelta(days=(6 - today.weekday()))
    return start <= end_of_week and end >= today


def is_this_weekend(event):
    start, end = _event_dates(event)
    if start is None:
        return False
    today = datetime.now().date()
    days_to_fri = (4 - today.weekday()) % 7
    friday = today + timedelta(days=days_to_fri)
    sunday = friday + timedelta(days=2)
    return start <= sunday and end >= friday


def is_happening_now(event):
    start, end = _event_dates(event)
    if start is None:
        return False
    today = datetime.now().date()
    return start <= today <= end


def is_free(event):
    price = _s(event, "price").lower().strip()
    return price in ("free", "$0", "0")


def days_until(event):
    start, end = _event_dates(event)
    if start is None:
        return ""
    today = datetime.now().date()
    delta = (start - today).days
    if delta < 0:
        if end >= today:
            return "Now"
        return "Past"
    elif delta == 0:
        return "Today"
    elif delta == 1:
        return "Tomorrow"
    elif delta < 7:
        return f"In {delta} days"
    else:
        return f"In {delta // 7}w"


def gcal_url(event):
    start_str = _s(event, "date_start").replace("-", "")
    end_raw = _s(event, "date_end") or _s(event, "date_start")
    try:
        end_dt = datetime.strptime(end_raw, "%Y-%m-%d") + timedelta(days=1)
        end_str = end_dt.strftime("%Y%m%d")
    except Exception:
        end_str = start_str
    params = urllib.parse.urlencode({
        "action": "TEMPLATE",
        "text": _s(event, "title"),
        "dates": f"{start_str}/{end_str}",
        "details": _s(event, "description"),
        "location": _s(event, "venue"),
    })
    return f"https://calendar.google.com/calendar/render?{params}"


def maps_url(event):
    venue = _s(event, "venue")
    return f"https://www.google.com/maps/search/{urllib.parse.quote(venue + ' Philadelphia PA')}"


def share_url(event):
    """Generate a mailto: link to share event details with someone."""
    title = _s(event, "title")
    venue = _s(event, "venue")
    dates = _s(event, "date_display")
    link = _s(event, "link")
    desc = _s(event, "description")
    body = f"{title}\n{venue}\n{dates}\n\n{desc}\n\nTickets: {link}"
    params = urllib.parse.urlencode({
        "subject": f"Check out: {title} in Philly!",
        "body": body,
    }, quote_via=urllib.parse.quote)
    return f"mailto:?{params}"


def event_description(event, max_sentences=4):
    """Get event description, truncated to max_sentences. Generate rich fallback if empty."""
    desc = _s(event, "description").strip()

    if not desc:
        title = _s(event, "title")
        venue = _s(event, "venue")
        cats = _cats(event)
        price = _s(event, "price")
        time_str = _s(event, "time")
        venue_lower = venue.lower()

        # Venue-specific descriptions that are actually useful
        if "chris" in venue_lower and "jazz" in venue_lower:
            desc = (f"Live jazz at Chris' Jazz Cafe — Philadelphia's premier jazz club "
                    f"at 1421 Sansom Street in Center City. {title} takes the stage"
                    f"{' at ' + time_str if time_str else ''} for an intimate evening "
                    f"of world-class jazz. Full dinner menu and craft cocktails available. "
                    f"Reservations recommended.")
        elif "south jazz" in venue_lower:
            desc = (f"Live jazz at South Jazz Kitchen — Philly's vibrant jazz supper club "
                    f"in the heart of South Street. {title} performs"
                    f"{' at ' + time_str if time_str else ''} with Southern-inspired cuisine "
                    f"and signature cocktails. An intimate listening room experience.")
        elif "world cafe" in venue_lower:
            desc = (f"Live music at World Cafe Live — Philadelphia's beloved venue at "
                    f"3025 Walnut Street. {title} performs"
                    f"{' at ' + time_str if time_str else ''}. Two stages, full bar, "
                    f"and restaurant. All ages welcome in this iconic University City venue.")
        elif "city winery" in venue_lower:
            desc = (f"Live performance at City Winery Philadelphia — an intimate "
                    f"concert venue, restaurant, and winery in the Fashion District. "
                    f"{title} takes the stage{' at ' + time_str if time_str else ''}. "
                    f"Enjoy award-winning wines and a full dining experience.")
        elif "kimmel" in venue_lower or "marian anderson" in venue_lower:
            desc = (f"{title} at the Kimmel Cultural Campus — Philadelphia's premier "
                    f"performing arts center on the Avenue of the Arts. "
                    f"{'Tickets from ' + price + '.' if price else ''}")
        elif "academy of music" in venue_lower:
            desc = (f"{title} at the historic Academy of Music — the oldest opera house "
                    f"in the U.S. still used for its original purpose (since 1857). "
                    f"Located on the Avenue of the Arts in Center City Philadelphia.")
        elif "annenberg" in venue_lower or "penn live" in venue_lower:
            desc = (f"{title} at the Annenberg Center for the Performing Arts — Penn Live Arts' "
                    f"home on the University of Pennsylvania campus. A cornerstone of "
                    f"Philadelphia's cultural scene since 1971.")
        elif "perelman" in venue_lower:
            desc = (f"{title} at the Perelman Theater — an intimate 599-seat venue inside "
                    f"the Kimmel Cultural Campus, ideal for chamber music, jazz, and "
                    f"solo performances on the Avenue of the Arts.")
        elif "arden" in venue_lower:
            desc = (f"{title} at the Arden Theatre Company — Philadelphia's award-winning "
                    f"theater in Old City, known for bold reimaginings and intimate staging "
                    f"at 40 N. 2nd Street.")
        elif "wilma" in venue_lower:
            desc = (f"{title} at The Wilma Theater — one of Philadelphia's most adventurous "
                    f"theater companies on the Avenue of the Arts. Known for world premieres "
                    f"and daring interpretations.")
        elif "walnut" in venue_lower:
            desc = (f"{title} at the Walnut Street Theatre — America's oldest theater, "
                    f"founded in 1809. A Philadelphia landmark in the heart of the city's "
                    f"theater district.")
        elif "forrest" in venue_lower:
            desc = (f"{title} at the Forrest Theatre — Philadelphia's home for blockbuster "
                    f"Broadway touring productions since 1928, located at 1114 Walnut Street.")
        elif "fringearts" in venue_lower or "fringe" in venue_lower:
            desc = (f"{title} at FringeArts — Philadelphia's home for contemporary "
                    f"performance on the Delaware River waterfront. Experimental, bold, "
                    f"and always surprising.")
        elif "miller" in venue_lower:
            desc = (f"{title} at the Miller Theater — the newest jewel of the Kimmel "
                    f"Cultural Campus, a state-of-the-art venue on the Avenue of the Arts.")
        else:
            # Generic but still useful
            primary_cat = cats[0] if cats else ""
            cat_labels = {
                "jazz": "Live jazz", "classical": "Classical music",
                "musical": "Musical theater", "theater": "Live theater",
                "ballet": "Ballet", "dance": "Dance performance",
                "opera": "Opera", "concert": "Live concert",
                "performance": "Live performance",
            }
            cat_label = cat_labels.get(primary_cat, "Live performance")
            desc = f"{cat_label} in Philadelphia"
            if venue:
                desc += f" at {venue}"
            desc += "."
            if price:
                desc += f" Tickets {'are free' if price.lower() == 'free' else price}."

    # Truncate to max_sentences
    sentences = _re.split(r'(?<=[.!?])\s+', desc)
    if len(sentences) > max_sentences:
        desc = " ".join(sentences[:max_sentences])
        if not desc.endswith((".", "!", "?")):
            desc += "."
    return desc


def category_badge_html(cat):
    color = CAT_COLORS.get(cat, "#a0aec0")
    icon = CAT_ICONS.get(cat, "")
    return f'<span style="background:{color}22;color:{color};padding:3px 12px;border-radius:12px;font-size:0.78rem;font-weight:600;margin-right:4px;text-transform:capitalize;">{icon} {cat}</span>'


def urgency_badge(event):
    label = days_until(event)
    if not label or label == "Past":
        return ""
    if label in ("Today", "Now"):
        return f'<span style="background:#ff6b9d22;color:#ff6b9d;padding:3px 10px;border-radius:12px;font-size:0.75rem;font-weight:700;margin-left:8px">🔴 {label}</span>'
    elif label == "Tomorrow":
        return f'<span style="background:#ffa44f22;color:#ffa44f;padding:3px 10px;border-radius:12px;font-size:0.75rem;font-weight:700;margin-left:8px">🟠 {label}</span>'
    else:
        return f'<span style="background:#4fd1c522;color:#4fd1c5;padding:3px 10px;border-radius:12px;font-size:0.75rem;font-weight:600;margin-left:8px">{label}</span>'


def events_to_csv(events):
    """Convert list of events to CSV string for download/export."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["Title", "Venue", "Start Date", "End Date", "Date Display", "Time",
                      "Price", "Categories", "Description", "Tickets URL", "Source"])
    for e in events:
        writer.writerow([
            _s(e, "title"),
            _s(e, "venue"),
            _s(e, "date_start"),
            _s(e, "date_end"),
            _s(e, "date_display"),
            _s(e, "time"),
            _s(e, "price"),
            ", ".join(_cats(e)),
            _s(e, "description"),
            _s(e, "link"),
            _s(e, "source"),
        ])
    return output.getvalue()


# ── Custom CSS ───────────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Inter:wght@300;400;500;600;700&display=swap');

.stApp { font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif; }

/* Hide default Streamlit elements for cleaner look */
#MainMenu {visibility: hidden;}
header {visibility: hidden;}
footer {visibility: hidden;}
div[data-testid="stDecoration"] {display: none;}

.main-title {
    font-family: 'Playfair Display', serif;
    font-size: 2.6rem;
    margin-bottom: -0.3rem;
    line-height: 1.2;
    letter-spacing: -0.02em;
}
.main-title .highlight {
    background: linear-gradient(135deg, #7c6aff, #a78bfa);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
}
.subtitle {
    color: #8888a0;
    font-size: 0.78rem;
    letter-spacing: 3px;
    text-transform: uppercase;
    margin-bottom: 1rem;
    font-weight: 400;
}

/* Stats — glassmorphism */
.stat-box {
    background: rgba(22, 22, 31, 0.7);
    backdrop-filter: blur(12px);
    -webkit-backdrop-filter: blur(12px);
    border: 1px solid rgba(124, 106, 255, 0.12);
    border-radius: 16px;
    padding: 0.9rem 1rem;
    text-align: center;
    transition: all 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94);
}
.stat-box:hover {
    border-color: rgba(124, 106, 255, 0.3);
    transform: translateY(-1px);
    box-shadow: 0 8px 24px rgba(124, 106, 255, 0.1);
}
.stat-value {
    font-size: 1.7rem;
    font-weight: 700;
    background: linear-gradient(135deg, #7c6aff, #a78bfa);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    line-height: 1.2;
}
.stat-label {
    font-size: 0.68rem;
    color: #8888a0;
    text-transform: uppercase;
    letter-spacing: 1.5px;
    font-weight: 500;
}

/* Event cards — Apple-quality glassmorphism */
.event-card {
    background: rgba(22, 22, 31, 0.65);
    backdrop-filter: blur(16px);
    -webkit-backdrop-filter: blur(16px);
    border: 1px solid rgba(255, 255, 255, 0.06);
    border-radius: 16px;
    padding: 1.1rem 1.3rem 0.9rem;
    margin-bottom: 0.3rem;
    transition: all 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94);
    display: flex;
    flex-direction: column;
    height: 100%;
}
.event-card:hover {
    border-color: rgba(124, 106, 255, 0.25);
    box-shadow: 0 8px 32px rgba(124, 106, 255, 0.08);
    transform: translateY(-2px);
}
.event-card-past {
    background: rgba(18, 18, 26, 0.5);
    border: 1px solid rgba(255, 255, 255, 0.03);
    border-radius: 14px;
    padding: 0.8rem 1.2rem;
    margin-bottom: 0.3rem;
    opacity: 0.6;
    transition: opacity 0.2s;
}
.event-card-past:hover { opacity: 0.8; }
.event-title {
    font-size: 1.05rem;
    font-weight: 600;
    color: #f0f0f8;
    margin-bottom: 0.25rem;
    letter-spacing: -0.01em;
    line-height: 1.3;
}
.event-meta {
    color: #8888a0;
    font-size: 0.82rem;
    margin-bottom: 0.2rem;
}
.event-venue { color: #a78bfa; font-weight: 500; font-size: 0.82rem; }
.event-desc {
    color: #c0c0d4;
    font-size: 0.84rem;
    line-height: 1.6;
    margin-top: 0.4rem;
    margin-bottom: 0.4rem;
    flex: 1;
}
.event-footer {
    display: flex;
    flex-wrap: wrap;
    gap: 5px;
    align-items: center;
    margin-top: auto;
    padding-top: 0.5rem;
}
.price-tag {
    background: rgba(104, 211, 145, 0.12);
    color: #68d391;
    padding: 2px 10px;
    border-radius: 20px;
    font-size: 0.72rem;
    font-weight: 600;
    letter-spacing: 0.02em;
}
/* Info pills — compact metadata tags */
.info-pill {
    display: inline-flex;
    align-items: center;
    gap: 3px;
    background: rgba(255, 255, 255, 0.04);
    border: 1px solid rgba(255, 255, 255, 0.06);
    color: #9999b0;
    padding: 2px 8px;
    border-radius: 6px;
    font-size: 0.72rem;
    font-weight: 500;
    white-space: nowrap;
}
.price-pill {
    background: rgba(104, 211, 145, 0.08);
    border-color: rgba(104, 211, 145, 0.15);
    color: #68d391;
}
/* Compact action icons row inside card */
.card-actions {
    display: flex;
    gap: 2px;
    margin-top: 0.5rem;
    padding-top: 0.5rem;
    border-top: 1px solid rgba(255, 255, 255, 0.04);
}
.card-actions a {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 4px;
    padding: 4px 10px;
    border-radius: 8px;
    font-size: 0.72rem;
    font-weight: 500;
    color: #8888a0;
    text-decoration: none;
    background: rgba(255, 255, 255, 0.03);
    border: 1px solid transparent;
    transition: all 0.2s ease;
    white-space: nowrap;
}
.card-actions a:hover {
    color: #a78bfa;
    background: rgba(124, 106, 255, 0.08);
    border-color: rgba(124, 106, 255, 0.15);
}
.month-header {
    font-family: 'Playfair Display', serif;
    font-size: 1.4rem;
    color: #f0f0f8;
    margin-top: 2rem;
    margin-bottom: 0.8rem;
    padding-bottom: 0.5rem;
    border-bottom: 1px solid rgba(255, 255, 255, 0.06);
    letter-spacing: -0.01em;
}

/* Spotlight — gradient glass */
.spotlight-card {
    background: linear-gradient(135deg, rgba(26, 26, 46, 0.8), rgba(22, 33, 62, 0.8));
    backdrop-filter: blur(16px);
    -webkit-backdrop-filter: blur(16px);
    border: 1px solid rgba(124, 106, 255, 0.2);
    border-radius: 18px;
    padding: 1.2rem 1.4rem;
    height: 100%;
    transition: all 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94);
}
.spotlight-card:hover {
    border-color: rgba(124, 106, 255, 0.4);
    box-shadow: 0 12px 40px rgba(124, 106, 255, 0.12);
    transform: translateY(-3px);
    cursor: pointer;
}
.spotlight-label {
    color: #a78bfa;
    font-size: 0.68rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 2.5px;
    margin-bottom: 0.5rem;
}

/* Coming up next */
.coming-up {
    background: rgba(18, 18, 26, 0.6);
    backdrop-filter: blur(8px);
    border: 1px solid rgba(255, 255, 255, 0.04);
    border-radius: 14px;
    padding: 0.8rem 1.1rem;
    margin-bottom: 0.4rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
    transition: all 0.2s ease;
}
.coming-up:hover {
    border-color: rgba(124, 106, 255, 0.15);
    background: rgba(18, 18, 26, 0.8);
}

/* Category chip used in filter bar */
.cat-chip {
    display: inline-block;
    padding: 4px 14px;
    border-radius: 20px;
    font-size: 0.82rem;
    font-weight: 600;
    cursor: pointer;
    margin-right: 4px;
    margin-bottom: 4px;
}

div[data-testid="stHorizontalBlock"] > div { padding: 0 0.3rem; }

/* Streamlit button styling — Apple-like */
.stButton > button {
    border-radius: 12px !important;
    font-weight: 500 !important;
    font-size: 0.75rem !important;
    padding: 0.35rem 0.5rem !important;
    transition: all 0.2s cubic-bezier(0.25, 0.46, 0.45, 0.94) !important;
    border: 1px solid rgba(255, 255, 255, 0.08) !important;
    letter-spacing: 0.01em !important;
    white-space: nowrap !important;
    overflow: hidden !important;
    text-overflow: ellipsis !important;
}
.stButton > button:hover {
    transform: translateY(-1px) !important;
    box-shadow: 0 4px 16px rgba(124, 106, 255, 0.15) !important;
}

/* Make link buttons match */
.stLinkButton > a {
    font-size: 0.75rem !important;
    padding: 0.35rem 0.5rem !important;
    border-radius: 12px !important;
    transition: all 0.2s cubic-bezier(0.25, 0.46, 0.45, 0.94) !important;
    border: 1px solid rgba(255, 255, 255, 0.08) !important;
    white-space: nowrap !important;
}
.stLinkButton > a:hover {
    transform: translateY(-1px) !important;
    box-shadow: 0 4px 16px rgba(124, 106, 255, 0.12) !important;
}

/* Selectbox styling */
.stSelectbox > div > div {
    border-radius: 12px !important;
}

/* Text input */
.stTextInput > div > div > input {
    border-radius: 12px !important;
}

/* Past events section */
.past-label {
    color: #55556a;
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 1.5px;
}

/* Export section */
.export-section {
    background: rgba(22, 22, 31, 0.6);
    border: 1px solid rgba(255, 255, 255, 0.05);
    border-radius: 16px;
    padding: 1rem 1.3rem;
    margin-bottom: 1rem;
}

/* Download button */
.stDownloadButton > button {
    border-radius: 12px !important;
}

/* Expander */
.streamlit-expanderHeader {
    border-radius: 14px !important;
}
</style>
""", unsafe_allow_html=True)


# ── Main ─────────────────────────────────────────────────────────────────────
def main():
    data = load_events()
    all_events = data.get("events", [])
    sources = data.get("sources", [])
    last_updated = data.get("last_updated", "")

    # ── Split into current and past events ────────────────────────────────
    current_events = [e for e in all_events if is_current_or_future(e)]
    past_events = [e for e in all_events if is_past(e)]
    past_events.sort(key=lambda e: _s(e, "date_start"), reverse=True)

    # ── Initialize session state ────────────────────────────────────────
    if "selected_ids" not in st.session_state:
        st.session_state.selected_ids = set()
    if "last_refresh" not in st.session_state:
        st.session_state.last_refresh = datetime.now()
    if "active_category" not in st.session_state:
        st.session_state.active_category = "all"

    # ── Header ───────────────────────────────────────────────────────────
    col_title, col_spacer, col_s1, col_s2, col_s3, col_refresh = st.columns([4, 0.5, 1, 1, 1, 1])
    with col_title:
        st.markdown('<div class="main-title">Philly<span class="highlight">Culture</span></div>', unsafe_allow_html=True)
        st.markdown('<div class="subtitle">Your guide to Philadelphia\'s performing arts</div>', unsafe_allow_html=True)
    with col_s1:
        st.markdown(f'<div class="stat-box"><div class="stat-value">{len(current_events)}</div><div class="stat-label">Events</div></div>', unsafe_allow_html=True)
    with col_s2:
        now_playing = sum(1 for e in current_events if is_happening_now(e))
        st.markdown(f'<div class="stat-box"><div class="stat-value">{now_playing}</div><div class="stat-label">Now Playing</div></div>', unsafe_allow_html=True)
    with col_s3:
        st.markdown(f'<div class="stat-box"><div class="stat-value">{len(sources)}</div><div class="stat-label">Sources</div></div>', unsafe_allow_html=True)
    with col_refresh:
        if st.button("🔄 Refresh", use_container_width=True):
            st.cache_data.clear()
            st.session_state.last_refresh = datetime.now()
            st.rerun()

    # ── Last refreshed line ──────────────────────────────────────────────
    refresh_str = st.session_state.last_refresh.strftime("%b %d, %Y at %I:%M %p")
    st.caption(f"Last refreshed: {refresh_str}")

    st.divider()

    # ── Search bar (full width, prominent) ──────────────────────────────
    search = st.text_input("Search", placeholder="🔍  Search events, venues, artists...", label_visibility="collapsed")

    # ── Compact filter row: venue, when, sort ────────────────────────────
    col_venue, col_time, col_sort = st.columns([2, 2, 1])

    with col_venue:
        all_venues = sorted({_s(e, "venue") for e in current_events if _s(e, "venue")})
        venue_filter = st.selectbox(
            "Venue",
            ["all"] + all_venues,
            format_func=lambda x: "📍 All Venues" if x == "all" else x,
            label_visibility="collapsed",
        )

    with col_time:
        time_filter = st.selectbox(
            "Time",
            ["all", "this_week", "this_weekend", "this_month", "free"],
            format_func=lambda x: {
                "all": "📅 All Dates",
                "this_week": "📅 This Week",
                "this_weekend": "🎉 This Weekend",
                "this_month": "📅 This Month",
                "free": "🆓 Free Events",
            }.get(x, x),
            label_visibility="collapsed",
        )

    with col_sort:
        sort_by = st.selectbox(
            "Sort",
            ["date", "name", "venue"],
            format_func=lambda x: {"date": "↕ Date", "name": "↕ Name", "venue": "↕ Venue"}.get(x, x),
            label_visibility="collapsed",
        )

    # ── Category chips (the primary way to filter by category) ────────
    all_cats = []
    for e in current_events:
        all_cats.extend(_cats(e))
    cat_counts = Counter(all_cats)
    if cat_counts:
        visible_cats = [c for c in ["theater", "musical", "jazz", "classical", "ballet", "dance", "opera", "concert", "performance"] if cat_counts.get(c, 0) > 0]
        # Cap at 7 categories + "All" = 8 chips max to prevent overflow
        visible_cats = visible_cats[:7]
        all_chips = ["all"] + visible_cats
        chip_cols = st.columns(len(all_chips))
        for i, cat in enumerate(all_chips):
            with chip_cols[i]:
                if cat == "all":
                    label = "All"
                else:
                    icon = CAT_ICONS.get(cat, "")
                    count = cat_counts[cat]
                    label = f"{icon} {cat.capitalize()} {count}"
                btn_type = "primary" if st.session_state.active_category == cat else "secondary"
                if st.button(label, use_container_width=True, type=btn_type, key=f"chip_{cat}"):
                    st.session_state.active_category = cat
                    st.rerun()

    # ── Apply filters (only to current/future events) ─────────────────────
    filtered = list(current_events)

    active_cat = st.session_state.active_category
    if active_cat != "all":
        filtered = [e for e in filtered if active_cat in _cats(e)]

    if venue_filter != "all":
        filtered = [e for e in filtered if _s(e, "venue") == venue_filter]

    if time_filter == "this_week":
        filtered = [e for e in filtered if is_this_week(e)]
    elif time_filter == "this_weekend":
        filtered = [e for e in filtered if is_this_weekend(e)]
    elif time_filter == "this_month":
        this_month = datetime.now().strftime("%Y-%m")
        filtered = [e for e in filtered if _s(e, "date_start").startswith(this_month)
                     or _s(e, "date_end").startswith(this_month)]
    elif time_filter == "free":
        filtered = [e for e in filtered if is_free(e)]

    if search:
        q = search.lower()
        filtered = [
            e for e in filtered
            if q in _s(e, "title").lower()
            or q in _s(e, "venue").lower()
            or q in _s(e, "description").lower()
            or q in _s(e, "source").lower()
            or any(q in c for c in _cats(e))
        ]

    if sort_by == "name":
        filtered.sort(key=lambda e: _s(e, "title").lower())
    elif sort_by == "venue":
        filtered.sort(key=lambda e: _s(e, "venue").lower())
    else:
        filtered.sort(key=lambda e: _s(e, "date_start", "9999"))

    # ── Spotlight: What's Happening Now ───────────────────────────────────
    tonight = [e for e in filtered if is_happening_now(e)]
    if tonight:
        st.markdown("#### 🔴 Happening Now")
        # Always use 4 columns so tiles don't stretch full-width
        cols = st.columns(4)
        for i, event in enumerate(tonight[:4]):
            with cols[i]:
                badges = "".join(category_badge_html(c) for c in _cats(event))
                price_html = f' <span class="price-tag">{_s(event, "price")}</span>' if _s(event, "price") else ""
                link = _s(event, "link")
                spot_desc = event_description(event, max_sentences=3)
                st.markdown(f"""
                <a href="{link}" target="_blank" rel="noopener" style="text-decoration:none;color:inherit;display:block">
                <div class="spotlight-card">
                    <div class="spotlight-label">Now Playing</div>
                    <div class="event-title">{_s(event, 'title')}</div>
                    <div class="event-meta"><span class="event-venue">{_s(event, 'venue')}</span></div>
                    <div class="event-meta">{_s(event, 'date_display')}{price_html}</div>
                    <div class="event-desc" style="margin-top:0.4rem;font-size:0.82rem">{spot_desc}</div>
                    <div style="margin-top:0.5rem">{badges}</div>
                    <div style="margin-top:0.6rem;font-size:0.78rem;color:#a78bfa;font-weight:500">🎟 Get Tickets →</div>
                </div>
                </a>
                """, unsafe_allow_html=True)
        st.markdown("")

    # ── Coming Up Next section ────────────────────────────────────────────
    upcoming = [e for e in filtered if not is_happening_now(e)]
    upcoming.sort(key=lambda e: _s(e, "date_start", "9999"))
    next_up = upcoming[:3]
    if next_up:
        st.markdown("#### Coming Up Next")
        for event in next_up:
            badge = urgency_badge(event)
            st.markdown(f"""
            <div class="coming-up">
                <div>
                    <span style="color:#e8e8f0;font-weight:600">{_s(event, 'title')}</span>
                    <span style="color:#8888a0;font-size:0.85rem"> at <span class="event-venue">{_s(event, 'venue')}</span></span>
                    {badge}
                </div>
                <div style="color:#8888a0;font-size:0.85rem;white-space:nowrap">{_s(event, 'date_display')}</div>
            </div>
            """, unsafe_allow_html=True)
        st.markdown("")

    st.divider()

    # ── Export bar (for selected events) ──────────────────────────────────
    selected_count = len(st.session_state.selected_ids)
    export_col1, export_col2, export_col3, export_col4 = st.columns([2, 1, 1, 1])
    with export_col1:
        st.caption(f"Showing {len(filtered)} of {len(current_events)} events  |  {selected_count} selected for export")
    with export_col2:
        if st.button("☑️ Select All Visible", use_container_width=True):
            for e in filtered:
                st.session_state.selected_ids.add(_s(e, "id"))
            st.rerun()
    with export_col3:
        if st.button("⬜ Clear Selection", use_container_width=True):
            st.session_state.selected_ids.clear()
            st.rerun()
    with export_col4:
        if selected_count > 0:
            selected_events = [e for e in all_events if _s(e, "id") in st.session_state.selected_ids]
            csv_data = events_to_csv(selected_events)
            st.download_button(
                "📥 Export CSV",
                csv_data,
                file_name="philly_culture_events.csv",
                mime="text/csv",
                use_container_width=True,
            )
        else:
            st.download_button(
                "📥 Export All CSV",
                events_to_csv(filtered),
                file_name="philly_culture_all_events.csv",
                mime="text/csv",
                use_container_width=True,
            )

    # ── Event listing grouped by month ───────────────────────────────────
    if not filtered:
        st.markdown("""
        <div style="text-align:center;padding:3rem;color:#8888a0">
            <div style="font-size:3rem;margin-bottom:1rem">🔍</div>
            <h3 style="color:#e8e8f0;margin-bottom:0.5rem">No events match your filters</h3>
            <p>Try adjusting your category, venue, date range, or search query.</p>
        </div>
        """, unsafe_allow_html=True)
    else:
        current_month = None
        # Render all events in a consistent 2-column grid
        col_idx = 0
        cols = None
        for event in filtered:
            month = get_month_key(_s(event, "date_start"))
            if month != current_month:
                # New month header — force new row
                current_month = month
                col_idx = 0
                cols = None
                st.markdown(f'<div class="month-header">{month}</div>', unsafe_allow_html=True)

            # Start new 2-column row when needed
            if col_idx % 2 == 0:
                cols = st.columns(2)

            with cols[col_idx % 2]:
                _render_event_card(event, st)
            col_idx += 1

    # ── Past Events Archive ───────────────────────────────────────────────
    if past_events:
        st.divider()
        with st.expander(f"📜 Past Events Archive ({len(past_events)} events)", expanded=False):
            st.caption("These events have already ended. Kept for reference.")
            for event in past_events:
                badges = "".join(category_badge_html(c) for c in _cats(event))
                price_html = f'<span class="price-tag">{_s(event, "price")}</span>' if _s(event, "price") else ""
                st.markdown(f"""
                <div class="event-card-past">
                    <div style="font-size:1rem;font-weight:600;color:#8888a0">{_s(event, 'title')}</div>
                    <div class="event-meta">
                        <span style="color:#6a6a8a">{_s(event, 'venue')}</span> · {_s(event, 'date_display')}
                        {' · ' + price_html if _s(event, 'price') else ''}
                    </div>
                    <div style="margin-top:0.3rem">{badges}</div>
                </div>
                """, unsafe_allow_html=True)

    # ── Sidebar: Analytics + Venue Explorer ───────────────────────────────
    with st.sidebar:
        st.markdown("### 📊 Analytics")
        st.markdown(f"**{len(current_events)}** upcoming · **{len(past_events)}** archived · **{len(sources)}** sources")
        st.markdown("")

        # Category breakdown
        st.markdown("**By Category**")
        for cat in sorted(cat_counts.keys(), key=lambda c: -cat_counts.get(c, 0)):
            color = CAT_COLORS.get(cat, "#a0aec0")
            icon = CAT_ICONS.get(cat, "")
            pct = cat_counts[cat] / max(len(current_events), 1) * 100
            st.markdown(
                f'<div style="margin-bottom:6px">'
                f'<span style="color:{color}">{icon} {cat.capitalize()}</span> '
                f'<span style="color:#8888a0">— {cat_counts[cat]} events</span>'
                f'<div style="background:#23233080;border-radius:4px;height:6px;margin-top:3px">'
                f'<div style="background:{color};width:{pct}%;height:100%;border-radius:4px"></div>'
                f'</div></div>',
                unsafe_allow_html=True
            )

        st.markdown("")
        st.markdown("**Top Venues**")
        venue_counts = Counter(_s(e, "venue", "Unknown") for e in current_events)
        for venue, count in venue_counts.most_common(8):
            st.markdown(f'<div style="color:#e8e8f0;font-size:0.9rem">{venue} <span style="color:#7c6aff;font-weight:600">({count})</span></div>', unsafe_allow_html=True)

        st.markdown("")
        st.markdown("**Monthly Distribution**")
        month_counts = Counter(get_month_key(_s(e, "date_start")) for e in current_events)
        def _month_sort_key(m):
            try:
                return datetime.strptime(m, "%B %Y")
            except Exception:
                return datetime.max
        for month in sorted(month_counts.keys(), key=_month_sort_key):
            count = month_counts[month]
            bar_w = count / max(month_counts.values(), 1) * 100
            st.markdown(
                f'<div style="margin-bottom:4px">'
                f'<span style="color:#e8e8f0;font-size:0.85rem">{month}</span> '
                f'<span style="color:#7c6aff;font-weight:600">{count}</span>'
                f'<div style="background:#23233080;border-radius:3px;height:5px;margin-top:2px">'
                f'<div style="background:#7c6aff;width:{bar_w}%;height:100%;border-radius:3px"></div>'
                f'</div></div>',
                unsafe_allow_html=True
            )

        st.markdown("")
        st.markdown("**Data Sources**")
        for source in sorted(sources):
            src_count = sum(1 for e in current_events if _s(e, "source") == source)
            st.markdown(f'<div style="color:#8888a0;font-size:0.85rem">• {source} <span style="color:#7c6aff">({src_count})</span></div>', unsafe_allow_html=True)

    # ── Footer ───────────────────────────────────────────────────────────
    st.divider()
    st.markdown(f"""
    <div style="text-align:center;color:#55556a;padding:1rem;font-size:0.85rem">
        <strong>PhillyCulture</strong> — Aggregating {len(sources)} Philadelphia performing arts sources<br>
        Data from verified public event listings. Not affiliated with any venue.
    </div>
    """, unsafe_allow_html=True)


def _render_event_card(event, st_ctx):
    """Render a single event card with integrated actions."""
    eid = _s(event, "id")
    badges = "".join(category_badge_html(c) for c in _cats(event))
    price = _s(event, "price")
    time_str = _s(event, "time")
    urg = urgency_badge(event)
    desc = event_description(event)
    link = _s(event, "link")
    venue = _s(event, "venue")
    date_disp = _s(event, "date_display")
    source = _s(event, "source")

    # Build compact info line
    meta_parts = []
    if date_disp:
        meta_parts.append(f'<span class="info-pill">📅 {date_disp}</span>')
    if time_str:
        meta_parts.append(f'<span class="info-pill">🕐 {time_str}</span>')
    if price:
        is_free = price.lower() == "free"
        meta_parts.append(f'<span class="info-pill price-pill">{"🆓" if is_free else "🎟"} {price}</span>')

    # Action links (inline HTML — no separate Streamlit buttons)
    action_links = []
    if link:
        action_links.append(f'<a href="{link}" target="_blank">🎟 Tickets</a>')
    action_links.append(f'<a href="{gcal_url(event)}" target="_blank">📅 Cal</a>')
    action_links.append(f'<a href="{maps_url(event)}" target="_blank">📍 Map</a>')
    action_links.append(f'<a href="{share_url(event)}" target="_blank">📤 Share</a>')
    actions_html = "".join(action_links)

    st_ctx.markdown(f"""
    <div class="event-card">
        <div class="event-title">{_s(event, 'title')}{urg}</div>
        <div class="event-venue">{venue}</div>
        <div class="event-desc">{desc}</div>
        <div class="event-footer">
            {" ".join(meta_parts)}
        </div>
        <div style="margin-top:0.4rem">{badges}</div>
        <div class="card-actions">
            {actions_html}
        </div>
    </div>
    """, unsafe_allow_html=True)

    # Select button (needs Streamlit interactivity)
    is_selected = eid in st.session_state.selected_ids
    sel_label = "✅ Selected" if is_selected else "☐ Select"
    if st_ctx.button(sel_label, key=f"sel_{eid}", use_container_width=True):
        if is_selected:
            st.session_state.selected_ids.discard(eid)
        else:
            st.session_state.selected_ids.add(eid)
        st.rerun()


if __name__ == "__main__":
    main()
