#!/usr/bin/env python3
"""
Seed Events — verified Philadelphia performing arts events from public sources.

These are real, verified events from Visit Philadelphia, Ensemble Arts Philly,
Theatre Philadelphia, Penn Live Arts, Opera Philadelphia, and other public listings.
They serve as baseline data when the live scraper cannot reach venue websites.

Last verified: 2026-03-23 via visitphilly.com, ensembleartsphilly.org,
theatrephiladelphia.org, pennlivearts.org, operaphila.org, walnutstreettheatre.org,
philadelphiaballet.org, balletx.org
"""

import hashlib
from datetime import datetime


def make_id(source, title, date_str=""):
    raw = f"{source}|{title}|{date_str}".lower().strip()
    return hashlib.md5(raw.encode()).hexdigest()[:12]


def get_seed_events():
    """Return list of verified Philadelphia cultural events for the current season."""
    events = [
        # ═══════════════════════════════════════════════════════════════════
        # CLASSICAL / ORCHESTRA
        # ═══════════════════════════════════════════════════════════════════
        {
            "title": "Mahler's Symphony No. 2",
            "date_start": "2026-03-06",
            "date_end": "2026-03-08",
            "venue": "Marian Anderson Hall, Kimmel Center",
            "source": "Philadelphia Orchestra",
            "source_url": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "link": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "price": None,
            "categories": ["classical"],
            "description": "Yannick Nézet-Séguin conducts Mahler's monumental Symphony No. 2 'Resurrection' featuring vocalists Ying Fang and Joyce DiDonato.",
        },
        {
            "title": "Yo-Yo Ma and Interlochen Center for the Arts",
            "date_start": "2026-03-13",
            "date_end": "2026-03-13",
            "venue": "Marian Anderson Hall, Kimmel Center",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "price": None,
            "categories": ["classical"],
            "description": "Legendary cellist Yo-Yo Ma performs with the Interlochen Center for the Arts to Celebrate America at 250.",
        },
        {
            "title": "The Young Person's Guide to the Orchestra",
            "date_start": "2026-03-14",
            "date_end": "2026-03-14",
            "venue": "Marian Anderson Hall, Kimmel Center",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "price": None,
            "categories": ["classical", "performance"],
            "description": "Part of the Family Discovery Series — an introduction to the orchestra for young audiences.",
        },
        {
            "title": "Brodsky Star Spotlight: Víkingur Ólafsson",
            "date_start": "2026-03-19",
            "date_end": "2026-03-19",
            "venue": "Marian Anderson Hall, Kimmel Center",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "price": None,
            "categories": ["classical"],
            "description": "Acclaimed Icelandic pianist Víkingur Ólafsson in the Brodsky Star Spotlight Series.",
        },
        {
            "title": "Marin Leads Rachmaninoff and Schumann",
            "date_start": "2026-03-20",
            "date_end": "2026-03-22",
            "venue": "Marian Anderson Hall, Kimmel Center",
            "source": "Philadelphia Orchestra",
            "source_url": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "link": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "price": None,
            "categories": ["classical"],
            "description": "The Philadelphia Orchestra performs Rachmaninoff and Schumann under the baton of conductor Marin Alsop.",
        },
        {
            "title": "Distant Worlds: Music from Final Fantasy",
            "date_start": "2026-03-21",
            "date_end": "2026-03-21",
            "venue": "Academy of Music",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "time": "8:00 PM",
            "price": None,
            "categories": ["classical", "concert"],
            "description": "The beloved music of Final Fantasy performed by a full symphony orchestra and chorus at the Academy of Music.",
        },
        {
            "title": "Sound All Around",
            "date_start": "2026-03-21",
            "date_end": "2026-03-23",
            "venue": "Kimmel Cultural Campus",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "price": None,
            "categories": ["classical", "performance"],
            "description": "Interactive musical experiences for all ages at the Kimmel Cultural Campus.",
        },
        {
            "title": "ECCO with Anthony McGill & Tai Murray",
            "date_start": "2026-03-31",
            "date_end": "2026-03-31",
            "venue": "Perelman Theater, Kimmel Center",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "time": "7:30 PM",
            "price": None,
            "categories": ["classical"],
            "description": "East Coast Chamber Orchestra performs with clarinetist Anthony McGill and violinist Tai Murray.",
        },
        {
            "title": "A Benefit Concert for the Musicians' Retirement Fund",
            "date_start": "2026-04-07",
            "date_end": "2026-04-07",
            "venue": "Marian Anderson Hall, Kimmel Center",
            "source": "Philadelphia Orchestra",
            "source_url": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "link": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "price": None,
            "categories": ["classical"],
            "description": "Annual benefit concert supporting the Philadelphia Orchestra's Musicians' Retirement Fund.",
        },
        {
            "title": "Mozart's Requiem",
            "date_start": "2026-04-09",
            "date_end": "2026-04-12",
            "venue": "Marian Anderson Hall, Kimmel Center",
            "source": "Philadelphia Orchestra",
            "source_url": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "link": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "price": None,
            "categories": ["classical"],
            "description": "The Philadelphia Orchestra performs Mozart's transcendent Requiem in D minor.",
        },
        {
            "title": "Bolero and Don Juan",
            "date_start": "2026-04-23",
            "date_end": "2026-04-25",
            "venue": "Marian Anderson Hall, Kimmel Center",
            "source": "Philadelphia Orchestra",
            "source_url": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "link": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "price": None,
            "categories": ["classical"],
            "description": "Ravel's electrifying Bolero paired with Strauss's Don Juan.",
        },
        {
            "title": "Copland's American Inspiration",
            "date_start": "2026-04-30",
            "date_end": "2026-05-02",
            "venue": "Marian Anderson Hall, Kimmel Center",
            "source": "Philadelphia Orchestra",
            "source_url": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "link": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "price": None,
            "categories": ["classical"],
            "description": "Matthias Pintscher leads Copland's most inspired American works.",
        },
        {
            "title": "Family Concert: Hip-Hop Orchestra",
            "date_start": "2026-05-02",
            "date_end": "2026-05-02",
            "venue": "Marian Anderson Hall, Kimmel Center",
            "source": "Philadelphia Orchestra",
            "source_url": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "link": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "time": "11:30 AM",
            "price": None,
            "categories": ["classical", "performance"],
            "description": "A family-friendly concert fusing hip-hop and orchestral music.",
        },
        {
            "title": "Orchestra After 5: Postcards from Spain",
            "date_start": "2026-05-14",
            "date_end": "2026-05-14",
            "venue": "Marian Anderson Hall, Kimmel Center",
            "source": "Philadelphia Orchestra",
            "source_url": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "link": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "time": "6:30 PM",
            "price": None,
            "categories": ["classical"],
            "description": "Bizet's Carmen Suite No. 1 and Falla's The Three-Cornered Hat in a relaxed after-work format.",
        },
        {
            "title": "Yannick Nézet-Séguin: Mahler & Sorey",
            "date_start": "2026-05-15",
            "date_end": "2026-05-16",
            "venue": "Marian Anderson Hall, Kimmel Center",
            "source": "Philadelphia Orchestra",
            "source_url": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "link": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "price": None,
            "categories": ["classical"],
            "description": "Music Director Yannick Nézet-Séguin conducts Mahler and Tyshawn Sorey.",
        },
        {
            "title": "Beethoven & Marsalis",
            "date_start": "2026-05-28",
            "date_end": "2026-05-30",
            "venue": "Marian Anderson Hall, Kimmel Center",
            "source": "Philadelphia Orchestra",
            "source_url": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "link": "https://philorch.ensembleartsphilly.org/tickets-and-events/2025-26-season",
            "price": None,
            "categories": ["classical", "jazz"],
            "description": "The Philadelphia Orchestra teams up with Jazz at Lincoln Center Orchestra to honor Beethoven and Wynton Marsalis.",
        },

        # ═══════════════════════════════════════════════════════════════════
        # JAZZ
        # ═══════════════════════════════════════════════════════════════════
        {
            "title": "Emmet Cohen: Miles and Coltrane at 100",
            "date_start": "2026-03-20",
            "date_end": "2026-03-20",
            "venue": "Perelman Theater, Kimmel Center",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "time": "7:30 PM",
            "price": None,
            "categories": ["jazz"],
            "description": "Pianist Emmet Cohen celebrates the centennials of Miles Davis and John Coltrane.",
        },
        {
            "title": "Endea Owens & The Cookout",
            "date_start": "2026-03-28",
            "date_end": "2026-03-28",
            "venue": "Perelman Theater, Kimmel Center",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "price": None,
            "categories": ["jazz"],
            "description": "The Late Show's bassist Endea Owens brings her dynamic ensemble The Cookout to the Jazz Series.",
        },
        {
            "title": "Pablo Batista: Latin Jazz Orchestra",
            "date_start": "2026-04-17",
            "date_end": "2026-04-17",
            "venue": "Esperanza Arts Center",
            "source": "Esperanza Arts Center",
            "source_url": "https://www.philaculture.org/events-calendar",
            "link": "https://www.philaculture.org/events-calendar",
            "price": None,
            "categories": ["jazz"],
            "description": "Grammy Award-winning percussionist Pablo Batista leads 20 big band musicians performing legendary Latin jazz.",
        },
        {
            "title": "Christian McBride & Edgar Meyer",
            "date_start": "2026-04-21",
            "date_end": "2026-04-21",
            "venue": "Perelman Theater, Kimmel Center",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "price": None,
            "categories": ["jazz"],
            "description": "Philly's own Christian McBride joined by fellow bassist Edgar Meyer in the Jazz Series.",
        },
        {
            "title": "Delbert Anderson Quartet: Beyond Belief",
            "date_start": "2026-04-26",
            "date_end": "2026-04-26",
            "venue": "Annenberg Center, Penn Live Arts",
            "source": "Penn Live Arts",
            "source_url": "https://pennlivearts.org/events/",
            "link": "https://pennlivearts.org/events/",
            "price": None,
            "categories": ["jazz"],
            "description": "A world premiere — Navajo trumpeter Delbert Anderson's three-part reflection on the relationship between the Navajo Nation and America.",
        },

        # ═══════════════════════════════════════════════════════════════════
        # THEATER
        # ═══════════════════════════════════════════════════════════════════
        {
            "title": "Romeo and Juliet",
            "date_start": "2026-03-12",
            "date_end": "2026-04-05",
            "venue": "Arden Theatre",
            "source": "Arden Theatre",
            "source_url": "https://ardentheatre.org/productions/",
            "link": "https://ardentheatre.org/productions/",
            "price": "$37 – $70",
            "categories": ["theater"],
            "description": "A bold reimagining of Shakespeare's star-crossed lovers at the Arden Theatre.",
        },
        {
            "title": "The Most Spectacularly Lamentable Trial of Miz Martha Washington",
            "date_start": "2026-03-17",
            "date_end": "2026-04-05",
            "venue": "The Wilma Theater",
            "source": "The Wilma Theater",
            "source_url": "https://www.wilmatheater.org/whats-on/",
            "link": "https://www.wilmatheater.org/whats-on/",
            "price": None,
            "categories": ["theater"],
            "description": "From Pulitzer Prize winner James Ijames — First Lady Martha Washington faces the enslaved people who will be freed upon her death. HotHouse Acting Company.",
        },
        {
            "title": "Sh!t-Faced Shakespeare",
            "date_start": "2026-03-20",
            "date_end": "2026-03-21",
            "venue": "Perelman Theater, Kimmel Center",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "price": None,
            "categories": ["theater"],
            "description": "The hilariously irreverent Shakespeare show where one cast member has had a few too many.",
        },
        {
            "title": "A Delicate Balance",
            "date_start": "2026-03-04",
            "date_end": "2026-03-29",
            "venue": "Walnut Street Theatre",
            "source": "Walnut Street Theatre",
            "source_url": "https://www.walnutstreettheatre.org/",
            "link": "https://www.walnutstreettheatre.org/season/mainstage.php",
            "price": "$33 – $247",
            "categories": ["theater"],
            "description": "Edward Albee's Pulitzer Prize-winning play — an absorbing look at the everyday hopes, fears, and secrets we all delicately balance. America's oldest theater.",
        },
        {
            "title": "The Stinky Cheese Man and Other Fairly Stupid Tales",
            "date_start": "2026-04-08",
            "date_end": "2026-05-31",
            "venue": "Arden Theatre",
            "source": "Arden Theatre",
            "source_url": "https://ardentheatre.org/productions/",
            "link": "https://ardentheatre.org/productions/",
            "price": None,
            "categories": ["theater", "performance"],
            "description": "Arden Children's Theatre presents the beloved tales in a zany, irreverent show for the whole family.",
        },
        {
            "title": "Wilderness Generation",
            "date_start": "2026-04-10",
            "date_end": "2026-05-03",
            "venue": "Suzanne Roberts Theatre",
            "source": "Philadelphia Theatre Company",
            "source_url": "https://www.philatheatreco.org/",
            "link": "https://www.philatheatreco.org/",
            "price": None,
            "categories": ["theater"],
            "description": "World premiere by James Ijames at Philadelphia Theatre Company. A compelling new work exploring identity and belonging.",
        },
        {
            "title": "Shucked",
            "date_start": "2026-04-21",
            "date_end": "2026-05-03",
            "venue": "Forrest Theatre",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "price": None,
            "categories": ["musical"],
            "description": "The hilarious Tony-nominated Broadway musical. A small-town comedy with heart, corn, and unforgettable laughs.",
        },
        {
            "title": "1776 The Musical",
            "date_start": "2026-05-05",
            "date_end": "2026-06-07",
            "venue": "Walnut Street Theatre",
            "source": "Walnut Street Theatre",
            "source_url": "https://www.walnutstreettheatre.org/",
            "link": "https://www.walnutstreettheatre.org/season/mainstage.php",
            "price": None,
            "categories": ["musical"],
            "description": "The Tony Award-winning musical about the signing of the Declaration of Independence — in the city where it happened.",
        },

        # ═══════════════════════════════════════════════════════════════════
        # BROADWAY / MUSICALS
        # ═══════════════════════════════════════════════════════════════════
        {
            "title": "TINA – The Tina Turner Musical",
            "date_start": "2026-03-10",
            "date_end": "2026-03-15",
            "venue": "Miller Theater, Kimmel Center",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "price": "From $87",
            "categories": ["musical"],
            "description": "The electrifying biographical musical about the Queen of Rock 'n' Roll at the Miller Theater.",
        },
        {
            "title": "The Sound of Music",
            "date_start": "2026-03-31",
            "date_end": "2026-04-05",
            "venue": "Academy of Music",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "price": None,
            "categories": ["musical"],
            "description": "Rodgers & Hammerstein's beloved classic at the Academy of Music. Directed by three-time Tony winner Jack O'Brien. Broadway Series.",
        },
        {
            "title": "The Outsiders",
            "date_start": "2026-05-26",
            "date_end": "2026-06-07",
            "venue": "Academy of Music",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "price": None,
            "categories": ["musical"],
            "description": "S.E. Hinton's classic novel brought to life as a Broadway musical at the Academy of Music.",
        },

        # ═══════════════════════════════════════════════════════════════════
        # BALLET / DANCE
        # ═══════════════════════════════════════════════════════════════════
        {
            "title": "The Merry Widow",
            "date_start": "2026-03-05",
            "date_end": "2026-03-15",
            "venue": "Academy of Music",
            "source": "Philadelphia Ballet",
            "source_url": "https://philadelphiaballet.org/performances/",
            "link": "https://philadelphiaballet.org/performances/",
            "price": None,
            "categories": ["ballet", "dance"],
            "description": "Philadelphia Ballet presents Ronald Hynd's celebrated choreography set to Franz Lehár's gorgeous music. A Parisian love story.",
        },
        {
            "title": "Rennie Harris Puremovement: Losing My Religion",
            "date_start": "2026-03-20",
            "date_end": "2026-03-21",
            "venue": "Annenberg Center, Penn Live Arts",
            "source": "Penn Live Arts",
            "source_url": "https://pennlivearts.org/events/",
            "link": "https://pennlivearts.org/events/",
            "price": None,
            "categories": ["dance"],
            "description": "World premiere fusing street dance and visual art. Rennie Harris abstractly examines our nation's cycle of injustice.",
        },
        {
            "title": "Explosive: Bold New Works on the Rise",
            "date_start": "2026-04-17",
            "date_end": "2026-04-19",
            "venue": "Perelman Theater, Kimmel Center",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "price": None,
            "categories": ["dance", "ballet"],
            "description": "Spring Residency — Philadelphia Ballet dancers perform explosive new choreography.",
        },
        {
            "title": "Paul Taylor Dance Company",
            "date_start": "2026-04-17",
            "date_end": "2026-04-18",
            "venue": "Annenberg Center, Penn Live Arts",
            "source": "Penn Live Arts",
            "source_url": "https://pennlivearts.org/event/PTDC2026",
            "link": "https://pennlivearts.org/event/PTDC2026",
            "price": None,
            "categories": ["dance"],
            "description": "One of America's most celebrated modern dance companies performs at the Annenberg Center.",
        },
        {
            "title": "BalletX Spring Series 2026",
            "date_start": "2026-03-27",
            "date_end": "2026-03-29",
            "venue": "Wilma Theater",
            "source": "BalletX",
            "source_url": "https://www.balletx.org/season-and-tickets/",
            "link": "https://www.balletx.org/seasons/spring-series-2026/",
            "price": None,
            "categories": ["ballet", "dance"],
            "description": "BalletX celebrates its 20th anniversary with three works by Matthew Neenan — Show Me, Broke Apart, and more.",
        },
        {
            "title": "Martha Graham Dance Company",
            "date_start": "2026-05-29",
            "date_end": "2026-05-30",
            "venue": "Annenberg Center, Penn Live Arts",
            "source": "Penn Live Arts",
            "source_url": "https://pennlivearts.org/event/MGDC2026",
            "link": "https://pennlivearts.org/event/MGDC2026",
            "price": None,
            "categories": ["dance"],
            "description": "The legendary Martha Graham Dance Company. Includes Tommie-Waheed Evans' 'in case of fire, speak' — co-commissioned with ArtPhilly.",
        },
        {
            "title": "Dance Theatre of Harlem",
            "date_start": "2026-04-03",
            "date_end": "2026-04-04",
            "venue": "Annenberg Center, Penn Live Arts",
            "source": "Penn Live Arts",
            "source_url": "https://pennlivearts.org/event/DTH2026",
            "link": "https://pennlivearts.org/event/DTH2026",
            "price": None,
            "categories": ["ballet", "dance"],
            "description": "Dance Theatre of Harlem brings its celebrated repertoire blending classical and contemporary ballet.",
        },

        # ═══════════════════════════════════════════════════════════════════
        # OPERA
        # ═══════════════════════════════════════════════════════════════════
        {
            "title": "Sleepers Awake (World Premiere)",
            "date_start": "2026-04-22",
            "date_end": "2026-04-26",
            "venue": "Academy of Music",
            "source": "Opera Philadelphia",
            "source_url": "https://www.operaphila.org/whats-on/events/",
            "link": "https://www.operaphila.org/whats-on/events/",
            "price": None,
            "categories": ["opera"],
            "description": "World premiere by composer Gregory Spears — inspired by the absurdist retelling of Sleeping Beauty by Robert Walser. Directed by Jenny Koons.",
        },
        {
            "title": "The Black Clown (Philadelphia Premiere)",
            "date_start": "2026-05-14",
            "date_end": "2026-05-17",
            "venue": "Miller Theater, Kimmel Center",
            "source": "Opera Philadelphia",
            "source_url": "https://www.operaphila.org/whats-on/events/",
            "link": "https://www.operaphila.org/whats-on/events/",
            "price": None,
            "categories": ["opera", "musical"],
            "description": "Based on Langston Hughes' poetry. Fuses vaudeville, gospel, opera, jazz, and spirituals.",
        },

        # ═══════════════════════════════════════════════════════════════════
        # PENN LIVE ARTS
        # ═══════════════════════════════════════════════════════════════════
        {
            "title": "Alarm Will Sound: American Stories",
            "date_start": "2026-03-13",
            "date_end": "2026-03-13",
            "venue": "Annenberg Center, Penn Live Arts",
            "source": "Penn Live Arts",
            "source_url": "https://pennlivearts.org/events/",
            "link": "https://pennlivearts.org/events/",
            "price": None,
            "categories": ["classical"],
            "description": "Contemporary ensemble Alarm Will Sound with Bora Yoon — diverse works exploring shifting perspectives and identities.",
        },
        {
            "title": "Ukulele Orchestra of Great Britain",
            "date_start": "2026-04-11",
            "date_end": "2026-04-11",
            "venue": "Annenberg Center, Penn Live Arts",
            "source": "Penn Live Arts",
            "source_url": "https://pennlivearts.org/events/",
            "link": "https://pennlivearts.org/events/",
            "price": None,
            "categories": ["concert"],
            "description": "'The best musical entertainment in the country' — from ABBA to Tchaikovsky, Nirvana to Broadway, all on ukuleles.",
        },
        {
            "title": "Tiburtina Ensemble: Celestial Harmony",
            "date_start": "2026-04-23",
            "date_end": "2026-04-23",
            "venue": "Annenberg Center, Penn Live Arts",
            "source": "Penn Live Arts",
            "source_url": "https://pennlivearts.org/events/",
            "link": "https://pennlivearts.org/events/",
            "price": None,
            "categories": ["classical"],
            "description": "Music for the Heavenly Court by Hildegard of Bingen — transcendent medieval vocal music.",
        },

        # ═══════════════════════════════════════════════════════════════════
        # FAMILY / OTHER
        # ═══════════════════════════════════════════════════════════════════
        {
            "title": "Peppa Pig: My First Concert",
            "date_start": "2026-04-04",
            "date_end": "2026-04-04",
            "venue": "Miller Theater, Kimmel Center",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "price": "From $63",
            "categories": ["performance"],
            "description": "Family Discovery Series. Ages 18 months and up. 1:00 PM and 4:00 PM shows.",
        },
        {
            "title": "Shen Yun",
            "date_start": "2026-04-15",
            "date_end": "2026-04-15",
            "venue": "Miller Theater, Kimmel Center",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "time": "7:30 PM",
            "price": "From $132",
            "categories": ["dance", "performance"],
            "description": "5,000 years of Chinese civilization brought to life through classical Chinese dance and a live orchestra.",
        },
        {
            "title": "Dog Man: The Musical",
            "date_start": "2026-04-25",
            "date_end": "2026-04-26",
            "venue": "Miller Theater, Kimmel Center",
            "source": "Ensemble Arts Philly",
            "source_url": "https://www.ensembleartsphilly.org/tickets-and-events",
            "link": "https://www.ensembleartsphilly.org/tickets-and-events",
            "price": None,
            "categories": ["musical", "performance"],
            "description": "Based on Dav Pilkey's best-selling series. Sensory Friendly Performance on Sunday, April 26.",
        },
        {
            "title": "Philadelphia Children's Festival",
            "date_start": "2026-05-03",
            "date_end": "2026-05-05",
            "venue": "Annenberg Center, Penn Live Arts",
            "source": "Penn Live Arts",
            "source_url": "https://pennlivearts.org/events/",
            "link": "https://pennlivearts.org/events/",
            "price": None,
            "categories": ["performance"],
            "description": "Family-friendly performances, hands-on activities, and outdoor PLAYground. Includes The Magic School Bus, Bill Blagg Magic, and more.",
        },
        {
            "title": "Girl Dolls: The American Musical",
            "date_start": "2026-05-09",
            "date_end": "2026-05-17",
            "venue": "FringeArts",
            "source": "FringeArts",
            "source_url": "https://fringearts.com/programs/",
            "link": "https://fringearts.com/programs/",
            "price": None,
            "categories": ["theater", "musical"],
            "description": "BYO your favorite doll — The Bearded Ladies Cabaret explores America's obsession with dolls, childhood, and identity.",
        },
    ]

    # Add computed fields
    for ev in events:
        date_str = ev.get("date_start", "")
        ev["id"] = make_id(ev["source"], ev["title"], date_str)
        s, e = ev.get("date_start", ""), ev.get("date_end", "")
        if s and e and s != e:
            try:
                sd = datetime.strptime(s, "%Y-%m-%d")
                ed = datetime.strptime(e, "%Y-%m-%d")
                ev["date_display"] = f"{sd.strftime('%b %d')} – {ed.strftime('%b %d, %Y')}"
            except ValueError:
                ev["date_display"] = f"{s} – {e}"
        elif s:
            try:
                sd = datetime.strptime(s, "%Y-%m-%d")
                ev["date_display"] = sd.strftime("%b %d, %Y")
            except ValueError:
                ev["date_display"] = s
        else:
            ev["date_display"] = ""
        ev.setdefault("time", None)
        ev.setdefault("description", None)

    return events
